name: Build and Upload macOS Package

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache FFmpeg
        id: cache-ffmpeg
        uses: actions/cache@v4
        with:
          path: ~/ffmpeg-cache
          key: ${{ runner.os }}-ffmpeg-${{ hashFiles('.github/ffmpeg-cache.lock') }}
          restore-keys: |
            ${{ runner.os }}-ffmpeg-


      - name: Build FFmpeg (if cache not hit)
        if: ${{ steps.cache-ffmpeg.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p ~/ffmpeg-cache
          touch ~/ffmpeg-cache/111
          echo 1234567 > ~/ffmpeg-cache/111

      - name: Failed Job
        shell: bash
        run: |
          exit 0
          # exit 1

      - name: Run Build and Upload Script
        shell: bash
        run: |
          ls ~/ffmpeg-cache
          cat ~/ffmpeg-cache/111