name: Build Pynini Environment

on:
  workflow_dispatch:

jobs:
  setup-conda-env:
    runs-on: windows-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v4

    - name: Install Mambaforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
        environment-file: ""
        auto-activate-base: true

    - name: Create Conda Env in conda-env
      shell: cmd
      run: |
        mkdir conda-env
        conda create -y -p .\conda-env python=3.10
        call conda activate .\conda-env
        conda install -y -c conda-forge pynini=2.1.6

    - name: Copy selected DLLs to ../DLLs
      shell: pwsh
      run: |
        ls conda-env/Library
        $srcDLLs = @(
          'conda-env/Library/bin/dl.dll',
          'conda-env/Library/bin/fst.dll',
          'conda-env/Library/bin/fstfar.dll',
          'conda-env/Library/bin/fstfarscript.dll',
          'conda-env/Library/bin/fstmpdtscript.dll',
          'conda-env/Library/bin/fstpdtscript.dll',
          'conda-env/Library/bin/fstscript.dll'
        )
        $dstDir = "DLLs"
        mkdir $dstDir -ea 0 | Out-Null
        foreach ($dll in $srcDLLs) {
          if (Test-Path $dll) {
            Copy-Item $dll -Destination $dstDir -Force
          } else {
            Write-Host "Missing: $dll"
          }
        }
        ls DLLs